#!/usr/bin/env python3

import os
import tempfile

import numpy as np

from ..design import fuzzball_composition_design

def design(args):
    """
    Design the context around the ligand in a protein-ligand complex

    Usage: bsff design <ligand_conformer_path> <match_path> <match_residue_map> <params_path> [options]

    Arguments:
      <ligand_conformer_path>           Path to ligand PDB generated by molfile_to_params.py
      <match_path>                      Path to scaffold-ligand match PDB
      <match_residue_map>               Pickle file generated by a bsff.assemble iteration
      <params_path>                     Path to the ligand params file generated by molfile_to_params.py

    Options:
      -c=<cstfile>, --match_cst=<cstfile>           Apply match constraints from .cst file during design
      -d=<dir>, --design_dir=<dir>                  Directory to dump designs into
      -h=<path>, --holesfilter=<path>               Path to DAlphaBall.gcc Holes Filter
      -l=<limit>, --rotset_limit=<limit>            Limit of rotamers added per residue identity per position
      -m, --apply_minimization                      Apply minimization before accepting/rejecting rotamers
      -n=<nstruct>, --nstruct=<nstruct>             Number of design trajectories to attempt
      -r=<rmsd>, --rmsd=<rmsd>                      RMSD to use for accepting complementary rotamerset rotamers
      -w=<weight>, --special_rot_weight=<weight>    Weight for complementary rotamers during design
      -x, --disable_rotamersets                     Don't use complementary rotamersets during design
    """
    ligand_conformer_path = args['<ligand_conformer_path>']
    match_path = args['<match_path>']
    match_residue_map = args['<match_residue_map>']
    params_path = args['<params_path>']

    design_dir = args['--design_dir'] if args['--design_dir'] else 'Designs'
    rotset_limit = int(args['--rotset_limit']) if args['--rotset_limit'] else 50
    nstruct = int(args['--nstruct']) if args['--nstruct'] else 1
    special_rot_weight = float(args['--special_rot_weight']) if args['--special_rot_weight'] else -2.5
    use_complementary_rotsets = not args['--disable_rotamersets']

    fuzzball_composition_design(ligand_conformer_path, match_path, match_residue_map,
                                params_path,
                                rotset_limit=rotset_limit, nstruct=nstruct,
                                apply_minimization=args['--apply_minimization'],
                                special_rot_weight=special_rot_weight, designdir=design_dir,
                                use_complementary_rotsets=use_complementary_rotsets,
                                match_cst=args['--match_cst'],
                                dalphaball_path=args['--holesfilter'])
